apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: LoadBalancer
  ports:
  - name: prometheus-ui
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: backend
  selector:
    prometheus: prometheus