apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - name: backend
      protocol: TCP
      port: 80
      targetPort: backend-container-port
  type: LoadBalancer