apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: LoadBalancer
  ports:
  - name: prometheus-ui
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: prometheus
